# Render Deploy Configuration

# This file tells Render how to deploy your Flask app.
# Place this file in the root of your repository and name it render.yaml (not in .github/workflows/).

services:
  - type: web
    name: flask-hello-world
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    plan: free
    envVars:
      - key: FLASK_ENV
        value: production
    autoDeploy: true
